### ISSUE TITLE
Please add documentation on how to login to app

### ISSUE THREAD

**Issue by donenoyes** [blackbracken/neji-android#54]
Can you please add instructions on how to get these values of Firebase, email, password?

Please add some documentation on how to successfully login to this app. Thank you.

![Uploading k_2021-04-24_16-45-04.png…]()

**Comment by blackbracken** [comment]
Hello!

I'm making this app mainly for my friends, so I can't provide enough support. Is that ok?
Anyway, I've described how to create a firebase project for this app and how to login in [README.md](https://github.com/blackbracken/neji-android/blob/master/README.md). Please refer to it if you need.

Thanks for your interest in this repository.
